import time

INSERTER = 1
SELECTOR = 1
BATCH = 100
EPOCH = 100

rule setup:
    """시스템 설치."""
    output: "temp/setup.json"
    shell:
        """
        cd deploy
        terraform apply -var-file=test.tfvars -auto-approve
        terraform output -json > ../{output}
        """

rule copy_setup:
    """설치 정보 복사."""
    input:
        "temp/setup.json"
    output:
        "temp/copy_setup"
    shell:
        """
        # Inserter
        ip=$(cat temp/setup.json | jq -r .inserter_public_ip.value)
        pkey=$(cat temp/setup.json | jq -r .private_key_path.value)
        ssh -o "StrictHostKeyChecking=no" ubuntu@$ip -i $pkey "cd dbztest/mssql && mkdir -p temp && mkdir -p temp"
        scp -i $pkey {input} ubuntu@$ip:dbztest/{input}
        # Selector
        ip=$(cat temp/setup.json | jq -r .selector_public_ip.value)
        pkey=$(cat temp/setup.json | jq -r .private_key_path.value)
        ssh -o "StrictHostKeyChecking=no" ubuntu@$ip -i $pkey "cd dbztest/mssql && mkdir -p temp && touch -p temp"
        scp -i $pkey {input} ubuntu@$ip:dbztest/mssql/{input}
        touch {output}
        """

rule inserter:
    """더미 데이터 인서트.

    인서트 전용 노드에서 실행.

    """
    input:
        "temp/setup.json",
        "temp/copy_setup",
        "temp/reset_table"
    output:
        "temp/inserter_{pid}.txt"
    params:
        pid="{pid}",
        epoch=EPOCH,
        batch=BATCH
    shell:
        """
        ip=$(cat temp/setup.json | jq -r .inserter_public_ip.value)
        pkey=$(cat temp/setup.json | jq -r .private_key_path.value)
        ssh ubuntu@$ip -i $pkey "cd dbztest/mssql && python3 inserter.py temp/setup.json {params.pid} {params.epoch} {params.batch} > {output}"
        scp -i $pkey ubuntu@$ip:dbztest/mssql/{output} {output}
        """


rule selector:
    """더미 데이터 셀렉트.

    셀렉트 전용 노드에서 실행

    """
    input:
        "temp/setup.json",
        "temp/copy_setup"
    output:
        "temp/selector_{pid}.txt"
    params:
        pid="{pid}"
    shell:
        """
        ip=$(cat temp/setup.json | jq -r .selector_public_ip.value)
        pkey=$(cat temp/setup.json | jq -r .private_key_path.value)
        ssh ubuntu@$ip -i $pkey "cd dbztest/mssql && python3 selector.py temp/setup.json {params.pid} > {output}"
        scp -i $pkey ubuntu@$ip:dbztest/mssql/{output} {output}
        """


rule reset_table:
    """인서트용 테이블 초기화."""
    input:
        "temp/setup.json"
    output:
        "temp/reset_table"
    script:
        "reset_table.py"


rule result:
    """테스트 결과."""
    input:
        expand("temp/inserter_{pid}.txt", pid=(range(INSERTER))),
        # select 를 동시에 하면 insert 성능이 저하
        # 단일 노드 insert/select 1680 -> 800
        # 전용 노드 insert/select 1680 -> 1000
        expand("temp/selector_{pid}.txt", pid=(range(SELECTOR)))
    params:
        start_time = time.time()
    output:
        "temp/result.txt"
    script:
        "result.py"


rule clear:
    """테스트 결과물 제거."""
    output:
        "temp/clear"
    shell:
        """
        # Inserter
        ip=$(cat temp/setup.json | jq -r .inserter_public_ip.value)
        pkey=$(cat temp/setup.json | jq -r .private_key_path.value)
        ssh ubuntu@$ip -i $pkey "pkill python3" || true
        # Selector
        ip=$(cat temp/setup.json | jq -r .selector_public_ip.value)
        ssh ubuntu@$ip -i $pkey "pkill python3" || true
        rm -f temp/reset_table
        rm -f temp/inserter_*.txt
        rm -f temp/selector_*.txt
        rm -f temp/result.txt
        rm -f temp/start_time
        touch {output}
        """

rule destroy:
    """시스템 제거."""
    output:
        "temp/destroy"
    shell:
        """
        rm -fr temp
        mkdir temp
        cd deploy
        terraform destroy -var-file=test.tfvars -auto-approve
        touch ../{output}
        """